services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8000:3000"
    env_file: .env
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    env_file: .env
    environment:
      - DISABLE_WORKER=true
      - NODE_ENV=production
    depends_on:
      - postgres
      - redis
    volumes:
      - ./volumes/media_ro:/app/media:ro
      - ./volumes/cache_rw:/app/cache:rw

  backend-worker:
    build:
      context: ./backend
    env_file: .env
    environment:
      - DISABLE_API=true
      - NODE_ENV=production
    depends_on:
      - postgres
      - redis
    volumes:
      - ./volumes/media_ro:/app/media:ro
      - ./volumes/cache_rw:/app/cache:rw

  postgres:
    image: ankane/pgvector:v0.5.1
    env_file: .env
    volumes:
      - ./volumes/pg_data:/var/lib/postgresql/data
      - ./volumes/pg_init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    env_file: .env
    volumes:
      - ./volumes/redis_data:/data
    ports:
      - "8003:6379"

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    env_file: .env
    ports:
      - "8004:3003"
    volumes:
      - ./volumes/ml_cache:/cache
