FROM node:22-alpine

RUN apk update && apk add --no-cache \
    ffmpeg \
    libheif-tools \
    libva \
    mesa-va-gallium

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]
