<script lang="ts">
  import { onMount } from 'svelte';
  import { API_BASE } from '$lib/api/media';
  import { ChevronLeft, Trash2, Link as LinkIcon, Folder, Image } from '@lucide/svelte';
  import Modal from '$lib/components/Modal.svelte';

  let shares: any[] = [];
  let isLoading = true;
  let showRevokeConfirm = false;
  let revokeTargetToken = '';

  async function fetchShares() {
    try {
      const token = localStorage.getItem('token');
      const res = await fetch(`${API_BASE}/api/admin/shares`, {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (res.ok) {
        const data = await res.json();
        shares = data.shares || [];
      }
    } catch (e) {
      console.error(e);
    } finally {
      isLoading = false;
    }
  }

  async function revokeShare(token: string) {
    revokeTargetToken = token;
    showRevokeConfirm = true;
  }

  async function confirmRevokeShare() {
    try {
      const jwt = localStorage.getItem('token');
      const res = await fetch(`${API_BASE}/api/admin/shares/${revokeTargetToken}`, {
        method: 'DELETE',
        headers: { 'Authorization': `Bearer ${jwt}` }
      });
      if (res.ok) {
        shares = shares.filter(s => s.share_token !== revokeTargetToken);
      }
    } catch (e) {
      console.error(e);
    } finally {
      showRevokeConfirm = false;
      revokeTargetToken = '';
    }
  }

  onMount(() => {
    fetchShares();
  });
</script>

<div class="admin-container">
  <div class="header">
    <h2>Active Shares</h2>
    <p style="color: #a1a1aa; margin-top: 0.5rem;">View and manage all active share links generated by users.</p>
  </div>

  {#if isLoading}
    <p>Loading shares...</p>
  {:else if shares.length === 0}
    <div class="glass-panel" style="text-align: center; padding: 3rem;">
      <LinkIcon size={48} color="#a1a1aa" style="margin-bottom: 1rem; opacity: 0.5;" />
      <h3 style="color: #f4f4f5; margin-bottom: 0.5rem;">No Active Shares</h3>
      <p style="color: #a1a1aa;">Users haven't generated any share links yet.</p>
    </div>
  {:else}
    <div class="table-container">
      <table class="glass-table">
        <thead>
          <tr>
            <th>Target</th>
            <th>Type</th>
            <th>Permissions</th>
            <th>Views / DLs</th>
            <th>Created</th>
            <th>Expires</th>
            <th style="text-align: right;">Actions</th>
          </tr>
        </thead>
        <tbody>
          {#each shares as share}
            <tr>
              <td>
                <div style="display: flex; align-items: center; gap: 8px;">
                  {#if share.folder_path}
                    <Folder size={16} color="#60a5fa" />
                    <span style="font-family: monospace; color: #93c5fd;">{share.folder_path}</span>
                  {:else}
                    <Image size={16} color="#f472b6" />
                    <span style="font-family: monospace; color: #fbcfe8;">{share.media_id}</span>
                  {/if}
                </div>
                <div style="font-size: 0.75rem; color: #64748b; margin-top: 4px; font-family: monospace;">
                  {share.share_token}
                </div>
              </td>
              <td>
                <span class="badge" class:folder={share.folder_path}>
                  {share.folder_path ? 'Folder' : 'Single Item'}
                </span>
              </td>
              <td>
                <div style="display: flex; flex-direction: column; gap: 4px; font-size: 0.8rem;">
                  {#if share.allow_download_images}
                    <span style="color: #34d399;">✓ Img DL</span>
                  {:else}
                    <span style="color: #ef4444;">✗ Img DL</span>
                  {/if}
                  
                  {#if share.allow_download_folder}
                    <span style="color: #34d399;">✓ Zip DL</span>
                  {:else}
                    <span style="color: #ef4444;">✗ Zip DL</span>
                  {/if}
                </div>
              </td>
              <td>
                <div style="display: flex; flex-direction: column; gap: 4px; font-size: 0.85rem;">
                  <span style="color: #94a3b8;">Views: <strong style="color: #f8fafc;">{share.views || 0}</strong></span>
                  <span style="color: #94a3b8;">DLs: <strong style="color: #f8fafc;">{share.downloads || 0}</strong></span>
                </div>
              </td>
              <td style="color: #94a3b8; font-size: 0.85rem;">
                {new Date(share.created_at).toLocaleDateString()}
              </td>
              <td style="color: #94a3b8; font-size: 0.85rem;">
                {#if share.expires_at}
                  {#if new Date(share.expires_at) < new Date()}
                    <span style="color: #ef4444;">Expired</span>
                  {:else}
                    {new Date(share.expires_at).toLocaleDateString()}
                  {/if}
                {:else}
                  Never
                {/if}
              </td>
              <td style="text-align: right;">
                <button class="icon-btn danger" onclick={() => revokeShare(share.share_token)} title="Revoke Share">
                  <Trash2 size={18} />
                </button>
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
</div>

<Modal bind:show={showRevokeConfirm} id="admin-revoke-confirm" title="Revoke Share Link">
  <p style="color: #ccc; margin-bottom: 24px; line-height: 1.5;">Are you sure you want to revoke this share link? Anyone using it will instantly lose access.</p>
  <div style="display: flex; justify-content: flex-end; gap: 1rem; margin-top: 1rem;">
    <button class="btn" style="background: transparent; border: 1px solid var(--glass-border); color: #ccc;" onclick={() => { showRevokeConfirm = false; revokeTargetToken = ''; }}>Cancel</button>
    <button class="btn" style="background: #ef4444; color: white; border: none;" onclick={confirmRevokeShare}>Revoke</button>
  </div>
</Modal>

<style>
  .admin-container {
    width: 100%;
    color: #f4f4f5;
  }
  
  .header {
    margin-bottom: 2rem;
  }
  
  h2 {
    font-size: 2rem;
    margin: 0;
  }

  .table-container {
    overflow-x: auto;
    background: var(--glass-bg);
    border: 1px solid var(--glass-border);
    border-radius: 12px;
  }

  .glass-table {
    width: 100%;
    border-collapse: collapse;
    text-align: left;
  }

  .glass-table th, .glass-table td {
    padding: 16px;
    border-bottom: 1px solid rgba(255,255,255,0.05);
  }

  .glass-table th {
    background: rgba(0,0,0,0.2);
    color: #a1a1aa;
    font-weight: 500;
    font-size: 0.85rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .badge {
    display: inline-block;
    padding: 4px 8px;
    border-radius: 12px;
    font-size: 0.75rem;
    font-weight: 600;
    background: rgba(244, 114, 182, 0.2);
    color: #fbcfe8;
    border: 1px solid rgba(244, 114, 182, 0.3);
  }
  
  .badge.folder {
    background: rgba(96, 165, 250, 0.2);
    color: #bfdbfe;
    border: 1px solid rgba(96, 165, 250, 0.3);
  }

  .icon-btn {
    background: none;
    border: none;
    color: #a1a1aa;
    cursor: pointer;
    padding: 8px;
    border-radius: 6px;
    transition: all 0.2s;
  }

  .icon-btn:hover {
    background: rgba(255,255,255,0.1);
    color: white;
  }

  .icon-btn.danger:hover {
    background: rgba(239, 68, 68, 0.2);
    color: #ef4444;
  }
</style>
