<script lang="ts">
  import { onMount } from 'svelte';
  import { copyToClipboard } from '$lib/utils/clipboard';
  import { env } from '$env/dynamic/public';
  import { API_BASE } from '$lib/api/media';
  import { ChevronLeft, Trash2, Link as LinkIcon, Folder, Image, User, Copy, Check, Edit, Power, PowerOff } from '@lucide/svelte';
  import Modal from '$lib/components/Modal.svelte';

  let shares: any[] = $state([]);
  let isLoading = $state(true);
  let showRevokeConfirm = $state(false);
  let revokeTargetToken = $state('');
  
  let showEditModal = $state(false);
  let editTargetToken = $state('');
  let editForm = $state({
    is_active: true,
    expires_at: '',
    allow_download_images: false,
    allow_download_folder: false,
    watermark_enabled: false
  });
  let copiedToken = $state('');

  async function fetchShares() {
    try {
      const token = localStorage.getItem('token');
      const res = await fetch(`${API_BASE}/api/admin/shares`, {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (res.ok) {
        const data = await res.json();
        shares = data.shares || [];
      }
    } catch (e) {
      console.error(e);
    } finally {
      isLoading = false;
    }
  }

  async function copyLink(token: string) {
    const domain = env.PUBLIC_APP_DOMAIN || window.location.origin;
    const url = `${domain}/share/${token}`;
    const success = await copyToClipboard(url);
    if (success) {
      copiedToken = token;
      setTimeout(() => { copiedToken = ''; }, 2000);
    }
  }

  function openEditShare(share: any) {
    editTargetToken = share.share_token;
    editForm = {
      is_active: share.is_active !== false,
      expires_at: share.expires_at ? new Date(share.expires_at).toISOString().slice(0, 16) : '',
      allow_download_images: share.allow_download_images || false,
      allow_download_folder: share.allow_download_folder || false,
      watermark_enabled: share.watermark_enabled || false
    };
    showEditModal = true;
  }

  async function saveShare() {
    try {
      const jwt = localStorage.getItem('token');
      const res = await fetch(`${API_BASE}/api/admin/shares/${editTargetToken}`, {
        method: 'PUT',
        headers: { 
          'Authorization': `Bearer ${jwt}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          is_active: editForm.is_active,
          expires_at: editForm.expires_at ? new Date(editForm.expires_at).toISOString() : null,
          allow_download_images: editForm.allow_download_images,
          allow_download_folder: editForm.allow_download_folder,
          watermark_enabled: editForm.watermark_enabled
        })
      });
      if (res.ok) {
        showEditModal = false;
        fetchShares();
      }
    } catch (e) {
      console.error(e);
    }
  }

  async function toggleDisable(share: any) {
    try {
      const jwt = localStorage.getItem('token');
      const res = await fetch(`${API_BASE}/api/admin/shares/${share.share_token}`, {
        method: 'PUT',
        headers: { 
          'Authorization': `Bearer ${jwt}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          is_active: share.is_active === false ? true : false
        })
      });
      if (res.ok) {
        fetchShares();
      }
    } catch (e) {
      console.error(e);
    }
  }

  async function revokeShare(token: string) {
    revokeTargetToken = token;
    showRevokeConfirm = true;
  }

  async function confirmRevokeShare() {
    try {
      const jwt = localStorage.getItem('token');
      const res = await fetch(`${API_BASE}/api/admin/shares/${revokeTargetToken}`, {
        method: 'DELETE',
        headers: { 'Authorization': `Bearer ${jwt}` }
      });
      if (res.ok) {
        shares = shares.filter(s => s.share_token !== revokeTargetToken);
      }
    } catch (e) {
      console.error(e);
    } finally {
      showRevokeConfirm = false;
      revokeTargetToken = '';
    }
  }

  onMount(() => {
    fetchShares();
  });
</script>

<div class="admin-container">
  <div class="header" style="display: flex; align-items: center; gap: 16px; margin-bottom: 32px;">
    <a href="/admin" class="icon-btn" style="text-decoration: none; display: flex; align-items: center; justify-content: center; width: 40px; height: 40px; background: rgba(255,255,255,0.05); border-radius: 50%; color: white;" title="Back to Admin Dashboard">
      <ChevronLeft size={24} />
    </a>
    <div>
      <h2 style="margin: 0;">Active Shares</h2>
      <p style="color: #a1a1aa; margin-top: 0.5rem; margin-bottom: 0;">View and manage all active share links generated by users.</p>
    </div>
  </div>

  {#if isLoading}
    <p>Loading shares...</p>
  {:else if shares.length === 0}
    <div class="glass-panel" style="text-align: center; padding: 3rem;">
      <LinkIcon size={48} color="#a1a1aa" style="margin-bottom: 1rem; opacity: 0.5;" />
      <h3 style="color: #f4f4f5; margin-bottom: 0.5rem;">No Active Shares</h3>
      <p style="color: #a1a1aa;">Users haven't generated any share links yet.</p>
    </div>
  {:else}
    <div class="table-container">
      <table class="glass-table">
        <thead>
          <tr>
            <th>Target</th>
            <th>Type</th>
            <th>Creator</th>
            <th>Permissions</th>
            <th>Views / DLs</th>
            <th>Status</th>
            <th>Created</th>
            <th>Expires</th>
            <th style="text-align: right;">Actions</th>
          </tr>
        </thead>
        <tbody>
          {#each shares as share}
            <tr>
              <td>
                <div style="display: flex; align-items: center; gap: 8px;">
                  {#if share.folder_path}
                    <Folder size={16} color="#60a5fa" />
                    <a href="/folder/{share.folder_path}" target="_blank" style="font-family: monospace; color: #93c5fd; text-decoration: none;">{share.folder_path}</a>
                  {:else}
                    <Image size={16} color="#f472b6" />
                    <a href="/share/{share.share_token}" target="_blank" style="font-family: monospace; color: #fbcfe8; text-decoration: none;">{share.media_id}</a>
                  {/if}
                </div>
                <div style="font-size: 0.75rem; margin-top: 4px; font-family: monospace;">
                  <a href="/share/{share.share_token}" target="_blank" style="color: #64748b; text-decoration: none;">{share.share_token}</a>
                </div>
              </td>
              <td>
                <span class="badge" class:folder={share.folder_path}>
                  {share.folder_path ? 'Folder' : 'Single Item'}
                </span>
              </td>
              <td>
                <div style="display: flex; align-items: center; gap: 8px;">
                  <User size={14} color="#94a3b8" />
                  <span style="color: #cbd5e1; font-size: 0.85rem;">{share.creator_email || 'System'}</span>
                </div>
              </td>
              <td>
                <div style="display: flex; flex-direction: column; gap: 4px; font-size: 0.8rem;">
                  {#if share.allow_download_images}
                    <span style="color: #34d399;">✓ Img DL</span>
                  {:else}
                    <span style="color: #ef4444;">✗ Img DL</span>
                  {/if}
                  
                  {#if share.allow_download_folder}
                    <span style="color: #34d399;">✓ Zip DL</span>
                  {:else}
                    <span style="color: #ef4444;">✗ Zip DL</span>
                  {/if}
                </div>
              </td>
              <td>
                <div style="display: flex; flex-direction: column; gap: 4px; font-size: 0.85rem;">
                  <span style="color: #94a3b8;">Views: <strong style="color: #f8fafc;">{share.views || 0}</strong></span>
                  <span style="color: #94a3b8;">DLs: <strong style="color: #f8fafc;">{share.downloads || 0}</strong></span>
                </div>
              </td>
              <td>
                {#if share.is_active === false}
                  <span class="badge" style="background: rgba(239, 68, 68, 0.2); color: #fca5a5; border-color: rgba(239, 68, 68, 0.3);">Disabled</span>
                {:else if share.expires_at && new Date(share.expires_at) < new Date()}
                  <span class="badge" style="background: rgba(245, 158, 11, 0.2); color: #fcd34d; border-color: rgba(245, 158, 11, 0.3);">Expired</span>
                {:else}
                  <span class="badge" style="background: rgba(52, 211, 153, 0.2); color: #86efac; border-color: rgba(52, 211, 153, 0.3);">Active</span>
                {/if}
              </td>
              <td style="color: #94a3b8; font-size: 0.85rem;">
                {new Date(share.created_at).toLocaleDateString()}
              </td>
              <td style="color: #94a3b8; font-size: 0.85rem;">
                {#if share.expires_at}
                  <span class:expired={new Date(share.expires_at) < new Date()}>
                    {new Date(share.expires_at).toLocaleDateString()}
                  </span>
                {:else}
                  Never
                {/if}
              </td>
              <td style="text-align: right;">
                <div style="display: flex; justify-content: flex-end; gap: 4px;">
                  <button class="icon-btn" onclick={() => copyLink(share.share_token)} title="Copy Link">
                    {#if copiedToken === share.share_token}
                      <Check size={16} color="#34d399" />
                    {:else}
                      <Copy size={16} />
                    {/if}
                  </button>
                  <button class="icon-btn" onclick={() => openEditShare(share)} title="Edit Share">
                    <Edit size={16} />
                  </button>
                  <button class="icon-btn" class:danger={share.is_active !== false} onclick={() => toggleDisable(share)} title={share.is_active === false ? 'Enable Share' : 'Disable Share'}>
                    {#if share.is_active === false}
                      <Power size={16} color="#34d399" />
                    {:else}
                      <PowerOff size={16} />
                    {/if}
                  </button>
                  <button class="icon-btn danger" onclick={() => revokeShare(share.share_token)} title="Delete Share">
                    <Trash2 size={16} />
                  </button>
                </div>
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
</div>

<Modal bind:show={showRevokeConfirm} id="admin-revoke-confirm" title="Revoke Share Link">
  <p style="color: #ccc; margin-bottom: 24px; line-height: 1.5;">Are you sure you want to revoke this share link? Anyone using it will instantly lose access.</p>
  <div style="display: flex; justify-content: flex-end; gap: 1rem; margin-top: 1rem;">
    <button class="btn" style="background: transparent; border: 1px solid var(--glass-border); color: #ccc;" onclick={() => { showRevokeConfirm = false; revokeTargetToken = ''; }}>Cancel</button>
    <button class="btn" style="background: #ef4444; color: white; border: none;" onclick={confirmRevokeShare}>Revoke</button>
  </div>
</Modal>

<Modal bind:show={showEditModal} id="admin-edit-share" title="Edit Share Link">
  <div class="form-group">
    <label>
      <input type="checkbox" bind:checked={editForm.is_active} />
      <span>Link is Active</span>
    </label>
  </div>
  
  <div class="form-group" style="margin-top: 1rem;">
    <label style="display: block; margin-bottom: 8px; color: #a1a1aa; font-size: 0.85rem;">Expires At (Optional)</label>
    <input type="datetime-local" bind:value={editForm.expires_at} style="width: 100%; padding: 10px; background: rgba(255,255,255,0.05); border: 1px solid rgba(255,255,255,0.1); border-radius: 8px; color: white;" />
  </div>

  <div class="form-group" style="margin-top: 1rem;">
    <label>
      <input type="checkbox" bind:checked={editForm.allow_download_images} />
      <span>Allow Image Downloads</span>
    </label>
  </div>

  <div class="form-group" style="margin-top: 0.5rem;">
    <label>
      <input type="checkbox" bind:checked={editForm.allow_download_folder} />
      <span>Allow Folder ZIP Download</span>
    </label>
  </div>

  <div class="form-group" style="margin-top: 0.5rem;">
    <label>
      <input type="checkbox" bind:checked={editForm.watermark_enabled} />
      <span>Enable Watermark</span>
    </label>
  </div>
  
  <div style="display: flex; justify-content: flex-end; gap: 1rem; margin-top: 2rem;">
    <button class="btn" style="background: transparent; border: 1px solid var(--glass-border); color: #ccc;" onclick={() => { showEditModal = false; }}>Cancel</button>
    <button class="btn" style="background: #3b82f6; color: white; border: none;" onclick={saveShare}>Save Changes</button>
  </div>
</Modal>

<style>
  .admin-container {
    width: 100%;
    color: #f4f4f5;
  }
  
  .header {
    margin-bottom: 2rem;
  }
  
  h2 {
    font-size: 2rem;
    margin: 0;
  }

  .table-container {
    overflow-x: auto;
    background: var(--glass-bg);
    border: 1px solid var(--glass-border);
    border-radius: 12px;
  }

  .glass-table {
    width: 100%;
    border-collapse: collapse;
    text-align: left;
  }

  .glass-table th, .glass-table td {
    padding: 16px;
    border-bottom: 1px solid rgba(255,255,255,0.05);
  }

  .glass-table th {
    background: rgba(0,0,0,0.2);
    color: #a1a1aa;
    font-weight: 500;
    font-size: 0.85rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .badge {
    display: inline-block;
    padding: 4px 8px;
    border-radius: 12px;
    font-size: 0.75rem;
    font-weight: 600;
    background: rgba(244, 114, 182, 0.2);
    color: #fbcfe8;
    border: 1px solid rgba(244, 114, 182, 0.3);
  }
  
  .badge.folder {
    background: rgba(96, 165, 250, 0.2);
    color: #bfdbfe;
    border: 1px solid rgba(96, 165, 250, 0.3);
  }

  .icon-btn {
    background: none;
    border: none;
    color: #a1a1aa;
    cursor: pointer;
    padding: 8px;
    border-radius: 6px;
    transition: all 0.2s;
  }

  .icon-btn:hover {
    background: rgba(255,255,255,0.1);
    color: white;
  }

  .icon-btn.danger:hover {
    background: rgba(239, 68, 68, 0.2);
    color: #ef4444;
  }
  
  .expired {
    color: #ef4444;
  }
  
  .form-group label {
    display: flex;
    align-items: center;
    gap: 12px;
    cursor: pointer;
    color: #f4f4f5;
  }
  
  .form-group input[type="checkbox"] {
    width: 18px;
    height: 18px;
    accent-color: #3b82f6;
  }

  @media (max-width: 900px) {
    h2 { font-size: 1.5rem; }
    .glass-table { min-width: 720px; }
  }
</style>
